# Generated by Django 4.1.3 on 2022-12-27 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default=None, upload_to='imagens', verbose_name='Image de perfil'),
        ),
    ]
