# Generated by Django 3.2.12 on 2022-12-11 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='genero_musical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genero', models.CharField(max_length=50, verbose_name='genero')),
            ],
        ),
        migrations.CreateModel(
            name='pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(max_length=50, verbose_name='país')),
            ],
        ),
        migrations.CreateModel(
            name='selo_fonografico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selo_fonografico', models.CharField(max_length=50, verbose_name='selo fonografico')),
            ],
        ),
        migrations.AlterModelOptions(
            name='disco',
            options={'verbose_name': 'Disco', 'verbose_name_plural': 'Discos'},
        ),
        migrations.AlterField(
            model_name='disco',
            name='genero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discos.genero_musical'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discos.pais'),
        ),
        migrations.AlterField(
            model_name='disco',
            name='selo_fonografico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discos.selo_fonografico'),
        ),
    ]
