# Generated by Django 3.2.12 on 2022-12-24 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discos', '0002_auto_20221211_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='genero_musical',
            options={'verbose_name': 'genero', 'verbose_name_plural': 'generos'},
        ),
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name': 'país', 'verbose_name_plural': 'países'},
        ),
        migrations.AlterModelOptions(
            name='selo_fonografico',
            options={'verbose_name': 'selo fonografico', 'verbose_name_plural': 'selos fonograficos'},
        ),
    ]
